[package]
name = "pbar"
version = "0.1.0"
authors = ["koushiro <https://github.com/koushiro>"]
description = "A terminal progress bar."
license = "MIT"
keywords = ["terminal", "progress", "bar", "cli"]

[dependencies]
terminal_size = "*"
regex = "*"